import React from "react";
import { ArrowRight, Check, FileSpreadsheet, ScanLine, ShieldCheck, Sparkles } from "lucide-react";
import { Link } from "react-router-dom";
import { BrandMark } from "@/components/BrandMark";
import { LangToggle } from "@/components/LangToggle";
import { ThemeToggle } from "@/components/ThemeToggle";
import { useLang } from "@/contexts/LangContext";

export default function Landing() {
  const { lang } = useLang();
  const en = lang === "en";
  const copy = en ? { eyebrow: "ANCLORA / DOCUMENT INTELLIGENCE", title: "From PDF tables to decisions you can trust.", lead: "TableExtract turns dense, messy PDFs into structured data you can review, validate and export — with confidence at cell level.", cta: "Request access", secondary: "Sign in", problem: "The last mile of document work is still manual.", problemLead: "Tables hide in reports, scans and invoices. TableExtract brings them into a calm, inspectable workspace without templates or spreadsheet archaeology.", benefits: ["Native extraction and OCR for scanned pages", "Deterministic normalization for dates and numbers", "Cell-by-cell confidence and review before export"], flow: ["Upload", "Inspect", "Export"], closing: "Make every table accountable." } : { eyebrow: "ANCLORA / INTELIGENCIA DOCUMENTAL", title: "De tablas PDF a decisiones en las que puedes confiar.", lead: "TableExtract convierte PDFs densos y desordenados en datos estructurados que puedes revisar, validar y exportar, con confianza celda a celda.", cta: "Solicitar acceso", secondary: "Iniciar sesión", problem: "El último tramo del trabajo documental sigue siendo manual.", problemLead: "Las tablas se esconden en informes, escaneos y facturas. TableExtract las lleva a un espacio calmado e inspeccionable, sin plantillas ni arqueología de hojas de cálculo.", benefits: ["Extracción nativa y OCR para páginas escaneadas", "Normalización determinista de fechas y números", "Confianza celda a celda antes de exportar"], flow: ["Cargar", "Revisar", "Exportar"], closing: "Haz que cada tabla sea trazable." };
  return <main className="landing-shell">
    <nav className="landing-nav"><Link to="/" className="landing-brand"><BrandMark className="h-10 w-10"/><span>Anclora <b>TableExtract</b></span></Link><div className="flex items-center gap-2"><a href="#how" className="landing-nav-link">{en ? "How it works" : "Cómo funciona"}</a><LangToggle/><ThemeToggle/><Link to="/login" className="landing-nav-cta">{copy.secondary}</Link></div></nav>
    <section className="landing-hero"><div className="landing-hero-copy fade-up"><p className="landing-eyebrow"><Sparkles size={14}/> {copy.eyebrow}</p><h1>{copy.title}</h1><p className="landing-lead">{copy.lead}</p><div className="landing-actions"><Link to="/login" className="landing-primary">{copy.cta}<ArrowRight size={17}/></Link><a href="#how" className="landing-text-link">{en ? "See the workflow" : "Ver el flujo"}<ArrowRight size={15}/></a></div><div className="landing-proof"><ShieldCheck size={17}/><span>{en ? "Private by design · invitation-only access" : "Privado por diseño · acceso mediante invitación"}</span></div></div><div className="landing-hero-visual fade-up" style={{animationDelay:"100ms"}}><div className="landing-orbit landing-orbit-one"/><div className="landing-orbit landing-orbit-two"/><div className="landing-product-card"><div className="landing-card-top"><span className="landing-live-dot"/><span>{en ? "REVIEW WORKSPACE" : "ESPACIO DE REVISIÓN"}</span><span className="ml-auto text-xs text-slate-400">98.4%</span></div><div className="landing-doc-preview"><div className="landing-doc-heading"/><div className="landing-doc-line w-2/3"/><div className="landing-table">{Array.from({length:12}).map((_,i)=><div key={i}/>)}</div></div><div className="landing-confidence"><span><i className="confidence-green"/> {en ? "Validated" : "Validado"}</span><span><i className="confidence-amber"/> {en ? "Review 3 cells" : "Revisar 3 celdas"}</span></div></div></div></section>
    <section className="landing-section landing-value"><p className="landing-eyebrow">{en ? "THE VALUE" : "EL VALOR"}</p><h2>{copy.problem}</h2><p className="landing-section-lead">{copy.problemLead}</p><div className="landing-benefits">{copy.benefits.map(item=><div key={item} className="landing-benefit"><span><Check size={15}/></span><p>{item}</p></div>)}</div></section>
    <section id="how" className="landing-section landing-flow"><div><p className="landing-eyebrow">{en ? "A QUIET, TRACEABLE FLOW" : "UN FLUJO CALMADO Y TRAZABLE"}</p><h2>{en ? "Move from document to dependable data." : "Del documento al dato fiable."}</h2></div><div className="landing-flow-grid">{copy.flow.map((item,i)=><div className="landing-flow-step" key={item}><span>0{i+1}</span><div>{i===0?<ScanLine/>:i===1?<ShieldCheck/>:<FileSpreadsheet/>}<h3>{item}</h3><p>{i===0?(en?"Drop in PDFs, including scans.":"Carga PDFs, también escaneados."):i===1?(en?"See confidence where it matters.":"Revisa la confianza donde importa."):(en?"Export clean, structured outputs.":"Exporta resultados estructurados.")}</p></div></div>)}</div></section>
    <section className="landing-closing"><p className="landing-eyebrow">{en ? "BUILT FOR THE WORK BETWEEN THE LINES" : "DISEÑADO PARA EL TRABAJO ENTRE LÍNEAS"}</p><h2>{copy.closing}</h2><Link to="/login" className="landing-primary">{copy.cta}<ArrowRight size={17}/></Link></section><footer className="landing-footer"><span>© Anclora TableExtract</span><span>{en ? "Secure document intelligence" : "Inteligencia documental segura"}</span><span><a href="/terms">{en ? "Terms" : "Términos"}</a> · <a href="/privacy">{en ? "Privacy" : "Privacidad"}</a></span></footer>
  </main>;
}
