import React, { useState } from "react";
import { Eye, EyeOff, Github, ArrowLeft } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { api } from "@/lib/api";
import { BrandMark } from "@/components/BrandMark";
import { LangToggle } from "@/components/LangToggle";
import { ThemeToggle } from "@/components/ThemeToggle";
import { useLang } from "@/contexts/LangContext";
import { useAuth } from "@/contexts/AuthContext";

export default function Login() {
  const { lang } = useLang(); const en = lang === "en"; const navigate = useNavigate(); const { setUser } = useAuth();
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [show,setShow]=useState(false); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  const login=async(e)=>{e.preventDefault();setBusy(true);setError("");try{const {data}=await api.post("/auth/login",{email,password});setUser(data);navigate("/upload")}catch{setError(en?"Unable to sign in with these details.":"No se pudo iniciar sesión con estos datos.")}finally{setBusy(false)}};
  const oauth=(provider)=>{const backend=process.env.REACT_APP_BACKEND_URL||"";window.location.href=`${backend}/api/auth/${provider}/start?redirect=%2Fupload`};
  return <main className="auth-shell"><div className="auth-top"><Link to="/" className="auth-back"><ArrowLeft size={15}/>{en?"Back to site":"Volver al sitio"}</Link><div className="flex gap-2"><LangToggle/><ThemeToggle/></div></div><div className="auth-glow auth-glow-one"/><div className="auth-glow auth-glow-two"/><section className="auth-card"><div className="auth-card-header"><BrandMark className="auth-logo"/><div className="auth-divider"/><p>Anclora TableExtract</p></div><form onSubmit={login} className="auth-form"><label htmlFor="email">{en?"Email":"Correo electrónico"}</label><input id="email" type="email" autoComplete="email" required aria-required="true" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@company.com"/><label htmlFor="password">{en?"Password":"Contraseña"}</label><div className="auth-password"><input id="password" type={show?"text":"password"} autoComplete="current-password" required aria-required="true" value={password} onChange={e=>setPassword(e.target.value)}/><button type="button" aria-label={show?(en?"Hide password":"Ocultar contraseña"):(en?"Show password":"Mostrar contraseña")} onClick={()=>setShow(!show)}>{show?<EyeOff size={16}/>:<Eye size={16}/>}</button></div>{error&&<div role="alert" className="auth-error">{error}</div>}<button className="auth-submit" disabled={busy}>{busy?(en?"Signing in…":"Iniciando sesión…"):(en?"Sign in":"Iniciar sesión")}</button><button type="button" className="auth-forgot" onClick={()=>setError(en?"Password recovery is handled by your invitation administrator.":"La recuperación se gestiona desde el administrador de invitaciones.")}>{en?"Forgot password?":"¿Has olvidado la contraseña?"}</button><div className="auth-invite">{en?"Access is currently invitation-only.":"El acceso está limitado a invitaciones."} <Link to="/" className="font-semibold">{en?"Request access":"Solicitar acceso"}</Link></div><div className="auth-social-label"><span/>{en?"Social access":"Acceso social"}<span/></div><div className="auth-social-grid"><button type="button" onClick={()=>oauth("google")}><span className="google-g">G</span>Google</button><button type="button" onClick={()=>oauth("github")}><Github size={16}/>GitHub</button></div><p className="auth-legal">{en?"By signing in you agree to our":"Al iniciar sesión aceptas nuestros"} <a href="/terms">{en?"Terms":"Términos"}</a> {en?"and":"y"} <a href="/privacy">{en?"Privacy":"Privacidad"}</a>.</p></form></section></main>;
}
